### PR TITLE
refactor: update translation strings for better redability

### PR DESCRIPTION
**Pull request by mrfelton**
## Description:

Update translation strings.

## Motivation and Context:

Better readability and consistency.

## How Has This Been Tested?

Manually

## Types of changes:

Updates to translation strings.

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

**Comment by mrfelton** [comment]
@lieteau2 I've made the adjustments as your your suggestions in Slack. Could you take a look please. There were 2 changes that I made:

1) I din't change `alias` to `alias name` since alias literally means name so using both words together doesn't make a whole lot of sense.

2) You suggested changing the title of the `Request` page to `Receive` which I have done, but in addition I also changed the wording of the `Request` button at the top of the wallet to `Receive` to match.

**Comment by lieteau2** [comment]
@mrfelton I've reviewed the changes per your request. 

I have a few requests. 

Screen Shot 2019-06-18 at 10 38 47 AM
here can we remove "through the lightning network" below "receive bitcoin"

and 
Screen Shot 2019-06-18 at 10 39 03 AM
for the onboarding process can we center the headers throughtout?

**Comment by mrfelton** [comment]
I've made those updates @lieteau2

**Comment by lieteau2** [comment]
For the onboarding, center the top header, keep bottom header left aligned.

Screen Shot 2019-06-18 at 2 34 48 PM

"Backup your channels" header needs to be centered
Screen Shot 2019-06-18 at 2 36 04 PM

"Welcome to your wallet" changed to "Welcome!"
Screen Shot 2019-06-18 at 2 36 56 PM

**Comment by mrfelton** [comment]
Updated @lieteau2 (with the exception of the change to the header alignment which doesn't work well).

Also, I changed the title `Backup Your Channels` to `Backup your channels` which better fits with all the other headings.

**Comment by lieteau2** [comment]
tested ACK 3ffaa31

**Pull request merged**
