### PR TITLE
scrollbars fix

### PR DESCRIPTION
**Pull request by odb366**
Fix for the unnecessary scrollbars in windows, issue #310

### CODE REVIEW

**Comment by odb366** [comment]
@Empact Done

**Comment by Empact** [comment]
@odb366 Could you take a look at your branch - right now there are a bunch of Jack's commits in your PR, whereas you'll want a feature branch including only your changes. A good move could be to create a new branch off of master and cherry-pick your changes to it.

**Comment by odb366** [comment]
@Empact Created a new PR: [scrollbar-fix2 #331](https://github.com/LN-Zap/zap-desktop/pull/331)
This pull request could be removed.

**Comment by Empact** [comment]
Closing in favor of #331

**Pull request closed without merging**
