### PR TITLE
Feature/minimize retype seed

### PR DESCRIPTION
**Pull request by JimmyMow**
We currently make our user retype all 24 words in their seed. This switches to the industry standard 3 random words, redesigns the form and also refactors the reducer and recovery form

### CODE REVIEW

**Comment by JimmyMow** [comment]
Really struggling with these commit hooks lol I have no idea how this turned out to be a 2 commit PR

**Comment by JimmyMow** [comment]
new form:

screen shot 2018-06-22 at 2 34 21 pm
screen shot 2018-06-22 at 2 33 39 pm

**Comment by Empact** [comment]
How about squashing these commits and adding a describing the change in the commit message? Right now both commits say they're fixing lints.

**Comment by JimmyMow** [comment]
@Empact squashed 2 bad commits and updated with 1 descriptive one

**Comment by JimmyMow** [comment]
@Empact rebased

**Comment by Empact** [comment]
Found the issue, see 728706c. Does that look good, or do you want to take a different approach?

**Comment by JimmyMow** [comment]
@Empact that looks good.

The line you removed was supposed to make sure there were sufficient entries but I think `reEnterSeedInput[index]` (first part of the conditional in the `every` func) does that as well.

👍

**Comment by Empact** [comment]
Tested ACK 530784a

**Pull request merged**
