### PR TITLE
build: auto release

### PR DESCRIPTION
**Pull request by mrfelton**
This PR adds automated release functionality to our CI process. This takes away most of the manual work of creating a release.

We use electron-builder for this.

After all the tests have passed on CI, electron-builder will check if a draft release exists on github and if it finds one it will build the project and attach the build artifacts to the release node.

This runs on travis (builds on/for osx and linux) and appvoyer (builds on/for windows).

Results look like this:

screenshot 2018-07-25 09 44 11

In order to integrate this you need to create a github access token with the `public_repo` permission and set it in the travis and appvoyer environment variables as `GH_TOKEN`.

Then, to trigger automate build publishing for an upcoming release:

1. Draft a new release. Set the “Tag version” to the value of version in your application package.json, and prefix it with v. “Release title” can be anything you want. For example, if your application package.json version is 1.0, your draft’s “Tag version” would be v1.0.
2. Push some commits. Every CI build will update the artifacts attached to this draft.
3. Once you are done, publish the release. GitHub will tag the latest commit for you.
The benefit of this workflow is that it allows you to always have the latest artifacts, and the release can be published once it is ready.

This follows the electron-builder recommended release flow:

https://www.electron.build/configuration/publish#recommended-github-releases-workflow

### CODE REVIEW

**Comment by mrfelton** [comment]
You can see an example of a successful build from there here:

https://travis-ci.org/mrfelton/zap-desktop/builds/407861306

screenshot 2018-07-25 20 03 32

**Comment by JimmyMow** [comment]
utACK 37bb20d

**Comment by Empact** [comment]
utACK 37bb20d

**Comment by mrfelton** [comment]
@Empact @JimmyMow I've given this PR some pretty extensive testing and now have the automated deployment process fully working. Once merged, every build on the master branch will build all electron targets and then attach to a github draft release whose tag matches the version number in package.json if one exists.

You can see the latest results of this here:

**Travis build that triggered the deployments:**
https://travis-ci.org/LN-Zap/zap-desktop/builds/408641606

**Draft github release with builds attached:**
https://github.com/LN-Zap/zap-desktop/releases/tag/untagged-6f67776ef89cc44961a1

As a follow up to this we will need to do https://github.com/LN-Zap/zap-desktop/issues/615 so that the builds are properly signed.

**Comment by JimmyMow** [comment]
utACK 1ac5271

**Pull request merged**
