### PR TITLE
feat: update lnd to v0.5.1-beta

### PR DESCRIPTION
**Pull request by mrfelton**
Update lnd to latest release.

### CODE REVIEW

**Comment by JimmyMow** [comment]
@mrfelton wanna update this to the official `0.5.1` release?

**Comment by mrfelton** [comment]
Updated to `v0.5.1-beta`

**Comment by JimmyMow** [comment]
Tested ACK 05eff40

**Comment by JimmyMow** [comment]
@mrfelton wanna give this a spin as well? if things are also working for you I'll merge

**Comment by mrfelton** [comment]
I'm good with this @JimmyMow

**Comment by JimmyMow** [comment]
\o/

**Pull request merged**
