### PR TITLE
feat(ui): allow user to choose denomination during onboarding setup

### PR DESCRIPTION
**Pull request by neb-b**
## Description:

Add the `<CryptoSelector />` component to the wallet setup screen to let users choose their bitcoin denomination while they set the max/min channel amounts

## Motivation and Context:

Closes #3721 

## How Has This Been Tested?

Manual testing. I haven't noticed any issues from my changes to the `ticker` selectors, but it seems like there could be potential side effects from those changes.

## Screenshots (if appropriate):

zap

## Types of changes:

New feature

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [x] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

**Review by mrfelton — CHANGES_REQUESTED** [review]
Getting some new warnings errors in the console from this, eg

> Warning: Failed prop type: The prop `cryptoUnit` is marked as required in `Home`, but its value is `null`.
    in Home (created by Context.Consumer)


> Warning: Failed prop type: The prop `cryptoUnit` is marked as required in `WalletLauncher`, but its value is `null`.
    in WalletLauncher (created by Context.Consumer)

**Comment by seanyesmunt** [comment]
Sorry about that. I'll give this another look.

**Comment by seanyesmunt** [comment]
@mrfelton Did you see those errors when running `yarn dev`? I'm not seeing them and `cryptoUnit` appears to be passed in correctly so that it's never `null`

**Comment by neb-b** [comment]
Realized this was still open today. Those warning messages led to some bigger issues I noticed related to my redux refactoring. I think this will require a different approach, or just more time making sure the selectors that were changed default to the correct value.

**Pull request closed without merging**
