### PR TITLE
Feature/lnd ipc renderer

### PR DESCRIPTION
**Pull request by jackmallers**
This removes the zap-nodejs library completely, no more express app needed. It leverages ipcRenderer within' electron. Makes the app much more friendly to non-technical users. Inching closer and closer to a great user experience

### CODE REVIEW

**Comment by fresheneesz** [comment]
@jackmallers Could you update the Readme to reflect your changes? Documentation changes should be part of commits that change the installation process or functionality for things that have instructions that appear in the readme.

**Comment by jackmallers** [comment]
@fresheneesz yeah that was mental error on my part. doing it now. thanks for pointing it out

**Comment by jackmallers** [comment]
@fresheneesz updated

**Comment by fresheneesz** [comment]
: D

**Pull request merged**
