### PR TITLE
fix(ui): don't open channel management modal when not needed

### LINKED ISSUE #3035: Closing "Open a Channel" modal opens channel management modal
This issue is on the `next` branch.

## Description

When you open "Open a Channel" modal and then try to close it you see the channel management modal. See video here: https://youtu.be/Cf7fG7Dl9M8

## Expected Behavior

See main wallet window when closing the "Open a channel" modal.

## Actual Behavior

See channel management UI instead.

## Possible Fix

Not sure but I think how modal are handle changed recently? @korhaliv probably knows.

## Your Environment

- Zap version: 0.6.0-alpha

### PR DESCRIPTION
**Pull request by bolatovumar**
## Motivation and Context:

fix #3035

## How Has This Been Tested?

Manually

- [x] My code follows the code style of this project.
- [ ] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

**Comment by bolatovumar** [comment]
@mrfelton, ok I will take a look. What I'm wondering is how this broke in the first place.

**Comment by bolatovumar** [comment]
@mrfelton now that I'm thinking about it, would you really want to land on the channel management screen after you initiated a channel. Once you have more than 2 channels if you are in card view or 4 channels if you are in list view, you have to scroll down to see the pending channel you just created. If you already have a couple of channels open, you probably don't really care to scroll down to see the "pending" channel and will just close the channel management pane. Does this make sense?

**Comment by mrfelton** [comment]
After creating a new channel, there is a period where we show the channel in ‘loading’ state prior to it becoming pending. In this state I think it shows at the top of the list - so newly opened channels should generally always show at the top of the list. I’m not 100% on how the selected sort mode affects that though.

**Comment by bolatovumar** [comment]
@mrfelton this doesn't seem to be the case (using the `master` branch). See video here: https://youtu.be/UOn0oO2lp0s

Is this a bug? Would you expect to show the newly "opened" channel at the top of the list? In that case it would make sense to show the channel management view once you initiate opening a channel. If that's not the case then going back to the wallet view makes sense.

**Comment by mrfelton** [comment]
Hmm. Interesting. This was the behavior in the past, but it looks like it no longer works this way since adding the ability to filter and sort the results.

This makes sense, because if you have your list set to show only online channels, ordered by activity (for example) then it wouldn't make sense to show loading or pending channels at the top of the list.

So, given this, and the fact that we do now also have a success notification that notifies the user if the channel was opened or not perhaps it does make sense to return the user to the wallet page if that is where they accessed the create channel form from.

**Comment by bolatovumar** [comment]
@mrfelton OK, I will fix up the issue with the tests and push it.

**Pull request merged**
