### PR TITLE
build(git): validate commit message format

### PR DESCRIPTION
**Pull request by mrfelton**
Our commit messages are a bit all over the place. Sometimes they sort of follow a standard, other times they don't.

Background:

https://chris.beams.io/posts/git-commit/

This PR installs `@commitlint/cli` and `@commitlint/config-conventional` along with `husky` and configures to automatically validate commit messages according to the Conventional Commit standard in a git pre-commit hook.

See:
  - http://conventionalcommits.org/
  - https://github.com/marionebl/commitlint
 
This makes it really for all contributors to provide commit messages that follow a globaly accepted standard.

Enforcing this would make it easier to use tools like `conventional-changelog` and `semantic-release` in the future which can also help to improve the quality of the project by adhering to other well accepted and adopted standards for open source projects.

See:

 - https://github.com/conventional-changelog/conventional-changelog
 - https://github.com/semantic-release/semantic-release

### CODE REVIEW

**Comment by JimmyMow** [comment]
Concept ACK 👏

**Comment by mrfelton** [comment]
This PR has been superseded by https://github.com/LN-Zap/zap-desktop/pull/440

**Comment by mrfelton** [comment]
Didn't mean to close the PR. This could be merged as is although https://github.com/LN-Zap/zap-desktop/pull/440 also includes and improves upon this commit, so merging that PR will effectually merge this one too.

**Comment by mrfelton** [comment]
@Empact  It's hard to split out the validate commit message stuff from the prettier stuff as the whole setup is a little interconnected.

I'm closing this PR in favour of the following 3:

https://github.com/LN-Zap/zap-desktop/pull/443
https://github.com/LN-Zap/zap-desktop/pull/442
https://github.com/LN-Zap/zap-desktop/pull/442

**Comment by Empact** [comment]
@mrfelton Is the commit message linting up anywhere? I don't see it in #440 for example.

**Pull request closed without merging**
