### PR TITLE
feat(home): display wallet config on settings page

### PR DESCRIPTION
**Pull request by mrfelton**
## Description:

Addition of key wallet config to wallet settings form (chain, network, host)

## Motivation and Context:

Provide users with useful information to help them understand what their wallets are.

## How Has This Been Tested?

- Storybook
- Manually in app

## Screenshots (if appropriate):

image

## Types of changes:

New Feature

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [ ] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

**Comment by JimmyMow** [comment]
@mrfelton I just set up one of my remote DO nodes with this branch and I'm not seeing my chain or network:

screen shot 2018-11-30 at 1 47 26 pm

No console errors or anything

**Comment by mrfelton** [comment]
@JimmyMow did you launch the node? The earliest that we can get that info is when we call 'getinfo' - which happens after fully launching the wallet.

**Comment by JimmyMow** [comment]
@mrfelton yeah I launched the node and then logged out

**Comment by JimmyMow** [comment]
@mrfelton nice! Tested ACK ce81cc2

**Pull request merged**
