### PR TITLE
Update react to latest v16.x

### PR DESCRIPTION
**Pull request by mrfelton**
Update react and all related packages to their latest versions. React 16 includes many improvements. There were only some minor changes needed to our source to support this version of react. In my limited testing everything appears to be working normally.

### CODE REVIEW

**Comment by Empact** [comment]
How about using classnames rather than ternary? https://github.com/JedWatson/classnames#usage
How about squashing the enzyme commit 7a97485 into a0c093a so that the tests pass on that commit?

**Comment by mrfelton** [comment]
rebased

**Comment by mrfelton** [comment]
rebased

**Comment by Empact** [comment]
Got this error:

screen shot 2018-07-18 at 09 56 56

**Comment by mrfelton** [comment]
This has been rebased and those issues should be resolved now

**Comment by JimmyMow** [comment]
I'm facing the same issues as @Empact

**Comment by mrfelton** [comment]
Rebased and resolved the issues.

**Comment by JimmyMow** [comment]
Getting the following console errors on start:

screen shot 2018-08-01 at 1 42 19 pm
screen shot 2018-08-01 at 1 42 11 pm

**Comment by mrfelton** [comment]
@JimmyMow I'm not able to reproduce your issue. Can you try `yarn clean && yarn install && yarn dev` please? Can you provide steps to reproduce?

**Comment by JimmyMow** [comment]
@mrfelton clearing my `~/Library/Application Support/Electron` works. 

Tested ACK 798a23e

Can you rebase this? Then we can get it merged

**Pull request merged**
