### PR TITLE
Feature/network

### PR DESCRIPTION
**Pull request by JimmyMow**

### CODE REVIEW

**Comment by JimmyMow** [comment]
@Empact what do you mean?

**Comment by Empact** [comment]
@JimmyMow the latest commit add a file at `resources/bin/darwin/lnd`

**Comment by joaodealmeida** [comment]
Just add a git ignore for the folders inside the /resource .

**Comment by Empact** [comment]
Gitignore lgtm, you'll need to remove this file as well: `resources/bin/darwin/lnd`

**Comment by JimmyMow** [comment]
removed @Empact, thanks. merging this cause we kinda are moving fast for public MVP soon

**Pull request merged**
