### PR TITLE
feat(testnet): add pill to UI on testnet

### PR DESCRIPTION
**Pull request by JimmyMow**
Add a Testnet pill to the UI next to our logo when a user is on testnet. Helps address #676 

screen shot 2018-08-21 at 6 19 33 pm

### CODE REVIEW

**Comment by odb366** [comment]
The pill diverts users attention to it way too much. In my opinion, we should use text only without it. The pill could also be mistaken for a button.

**Comment by mrfelton** [comment]
A agree it's possibly a little heavy. Perhaps just a green outline rather than a solid background colour?

**Comment by JimmyMow** [comment]
I got the design from our mobile app.

Changed the text color to match the rest of our wallet header and only made the border green. Thoughts @odb366 @mrfelton?

screen shot 2018-08-22 at 9 18 46 am

**Comment by JimmyMow** [comment]
Updated

**Comment by odb366** [comment]
@JimmyMow @mrfelton Now its good that it doesn't draw so much attention. However, I've shown the picture to the gf and 1 friend and they both thought that this was a button. I think we should use text-only so users don't mistake it for a button.

**Comment by JimmyMow** [comment]
@odb366 @mrfelton updated the UI:

screen shot 2018-09-04 at 10 32 13 am

**Comment by mrfelton** [comment]
LGTM

**Pull request merged**
