### PR TITLE
fix(reformat-request-form): fixed bad formatting

### PR DESCRIPTION
**Pull request by odb366**
Redesigned the request form so that it complies with usability laws and fits well on the default window size of ZAP.

zap-request-form

### CODE REVIEW

**Comment by Empact** [comment]
Is there a particular reason for leading with the amount?

**Comment by odb366** [comment]
In slack, at #desktop-design we discussed the request screen and @brandon shared a wireframe where the amount field was on top. We kind-a agreed to switch the fields there.

**Comment by Empact** [comment]
@odb366 Could you fix the test failure? It looks related.

Given the amount is required and the memo is not, I think leading with it is reasonable.

**Comment by odb366** [comment]
@Empact Done. Should I rebase?

**Comment by JimmyMow** [comment]
utACK https://github.com/LN-Zap/zap-desktop/pull/363/commits/193006aa0d048b97ac425ebf02dc352cdff73f90

I like the changes. Merging!

**Pull request merged**
