### PR TITLE
feat(wallet): sending payments in activity list

### PR DESCRIPTION
**Pull request by mrfelton**
## Description:

Show sending payments in the activity list.

**Note: This PR also includes the fix from #1056**

## Motivation and Context:

#1043

## How Has This Been Tested?

Test successful LN payment
Test failed LN payment
Test successful Onchain payment
Test failed Onchain payment

## Types of changes:

New Feeatures

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [x] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

**Comment by lieteau2** [comment]
Tested ACK 53d5ae3

**Comment by lieteau2** [comment]
Tested ACK da35464

**Comment by JimmyMow** [comment]
@mrfelton mind rebasing when you get a chance?

**Comment by mrfelton** [comment]
rebased @JimmyMow

**Pull request merged**
