### PR TITLE
feat(ui): add LightningInvoiceInput component

### PR DESCRIPTION
**Pull request by mrfelton**
## Description:

 - Implement a new form field component to handle input and validation of lightning invoices and bitcoin addresses.
 - Validates data according to BOLT standards.
 - Support Bitcoin and Litecoin address formats.

**Note:** This PR builds on the work done in #862 which should be merged first.

## Motivation and Context:

- Preparation for revamp of Pay/Request forms
- DRY up codebase

## How Has This Been Tested?

- `yarn storybook` and navigate to `Components / Form / Lightning Invoice Textarea`.
- Also see examples added to the `Components / Form / Example form`

Try entering valid/invalid values for each field and see validation pass/fail accordingly.

## Screenshots (if appropriate):

screenshot 2018-10-21 17 08 04

## Types of changes:

New feature

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [x] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

**Comment by JimmyMow** [comment]
@mrfelton Weird. I'm getting:

```
ERROR in ./.storybook/config.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/jmow/Projects/bolt/bolt-desktop/.storybook/config.js: Unexpected token, expected "," (15:24)
```

**Comment by mrfelton** [comment]
was a rebasing conflict. resolved now @JimmyMow

**Comment by JimmyMow** [comment]
@mrfelton can you rebase?

**Comment by JimmyMow** [comment]
Tested ACK 8b203f1

**Pull request merged**
