### PR TITLE
Add more logging for lnd service

### PR DESCRIPTION
**Pull request by mrfelton**
Log all calls to lnd service methods so that we can get a better picture of our intraprocess communication.

### CODE REVIEW

**Comment by JimmyMow** [comment]
utACK 9a6b886

**Comment by Empact** [comment]
This seems like a lower-level message to me, e.g. debug. Thoughts?

**Comment by mrfelton** [comment]
Debug is very very noisy. In https://github.com/LN-Zap/zap-desktop/pull/531 I have specifically reduced our default log level to `info`. These messages are very useful high-ish level info about what the app is doing and are very useful when included in the info level.

**Comment by Empact** [comment]
utACK 9a6b886

**Pull request merged**
