### PR TITLE
Changed linux instruction for tls.cert

### PR DESCRIPTION
**Pull request by callmekurisu**
~/.lnd/tls.cert path did not work for tls.cert but /home/user/.lnd/tls.cert did

### CODE REVIEW

**Comment by funyug** [comment]
The ~ refers to current user's directory same as /home/user/
Don't know why that didn't worked for you.

**Comment by callmekurisu** [comment]
yeah i know. it was strange. I have all the paths setup correctly

**Comment by jackmallers** [comment]
Hm, that's strange. I agree with @funyug and ~/.lnd works for me on my Linux machine.

Do any paths with `~` work for you?

**Comment by callmekurisu** [comment]
Yeah others do. Will find keep looking for this path error. Closing this request. Domo!

**Pull request closed without merging**
