### PR TITLE
refactor(utils): implement secureStorage util

### PR DESCRIPTION
**Pull request by korhaliv**
## Description:
Add the ability to store sensitive data in OS secure storage (macOS keychain, windows credentials manager, gnome keyring)

## Motivation and Context:
This will allow to store sensitive data such as lndconnect strings or access tokens in a more secure way

## How Has This Been Tested?
via tests

## Types of changes:
Refactor

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [x] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

**Comment by korhaliv** [comment]
yeah i saw. already fixed

**Comment by korhaliv** [comment]
@mrfelton there is however an issue with linux too. there is `libsecret` dependency

**Comment by mrfelton** [comment]
This needs a rebase @korhaliv

**Comment by korhaliv** [comment]
@mrfelton updated. i've also moved 
```
 onChange && onChange
``` 
out of `unblockLinkedUpdates`. Imo that code doesn't belong there semantically. Even though we have to call it twice now

**Comment by korhaliv** [comment]
updated

**Pull request merged**
