### PR TITLE
Update to webpack-command and webpack-serve

### PR DESCRIPTION
**Pull request by mrfelton**
`webpack-cli` is being depreciated in favour of `webpack-command` which provides many improvements and advantages.

See:
 - https://github.com/webpack-contrib/webpack-command#benefits
 - https://medium.com/webpack/webpacks-new-cli-hotness-d6a2063168a8
 - https://medium.com/webpack/unladen-swallows-and-the-deprecation-of-webpack-cli-39814f6694d3

`webpack-dev-server` is not compatible with `webpack-command`. It is also slow, old and in maintenance-only mode. So also migrate from `webpack-dev-server` to `webpack-serve` which is a more modern and faster alternative that is compatible with `webpack-serve`

See:
 - https://github.com/webpack/webpack-dev-server#project-in-maintenance
 - http://shellscape.org/2018/02/12/webpack-serve-up-whoopass

### CODE REVIEW

**Comment by Empact** [comment]
@mrfelton how about using `webpack-serve` 1.0.4 rather than the beta version?

**Comment by mrfelton** [comment]
@Empact I encountered some issues with the 1.x release that were blockers for us. I've been tracking the development of the 2.x release pretty closely for a while through https://github.com/webpack-contrib/webpack-serve/pull/189. They are very active with quite a lot of eyes on things. In my testing its working well.

Happy to wait until a stable release is cut though. I mostly just wanted to rebase this PR off master and get it out there so that it doesn't go stale in my local repo.

**Comment by Empact** [comment]
Sounds good, let's hold this pending a stable release.

**Comment by mrfelton** [comment]
webpack-serve 2.x is now officially out. https://github.com/webpack-contrib/webpack-serve/releases

I have updated this PR accordingly.

**Comment by Empact** [comment]
Tested ACK 8444607

**Pull request merged**
