### PR TITLE
feat(lnd): update lnd to latest master build

### PR DESCRIPTION
**Pull request by mrfelton**
Update lnd to v0.5-beta-rc2-60-g1c4bd04c

https://github.com/LN-Zap/lnd/releases/tag/v0.5-beta-rc2-60-g1c4bd04c

This build enables the experimental features which are needed for #748

### CODE REVIEW

**Comment by JimmyMow** [comment]
@mrfelton is this working for you? Getting `Lnd has unexpectedly quit: null`

**Comment by ZapUser77** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
Is what LND 0.5 reports when I start ZAP.  I'm using an older version of ZAP, I'll update to current and see if I still get the same error.

**Comment by mrfelton** [comment]
@JimmyMow I've updated this again this morning to use the latest lnd version (they released 0.5-beta this morning) and have tested this and confirmed it to be working.

I also made a couple of updates here to handle the termination process slightly differently which seems to be more reliable now (sending `SIGINT` to the process directly instead of using the grpc `stop` method).

I would suggest that you do `yarn clean && yarn` on this branch before retesting.

**Comment by JimmyMow** [comment]
Tested ACK 3326db1

**Pull request merged**
