### PR TITLE
feature(eslint-resolve-paths-from-app-dir): use 'app' path as default…

### PR DESCRIPTION
**Pull request by VonIobro**
… for imports

get rid of those ../../../../../paths^^

### CODE REVIEW

**Comment by jackmallers** [comment]
Nice! Do you wanna replace all annoying paths in this PR or merge the fix (in `.eslintrc`) and I can handle replacing all annoying paths later? @VonIobro

**Comment by VonIobro** [comment]
I can replace all the annoying paths in this PR. No problem.

**Comment by VonIobro** [comment]
The above commits have been tested and are ready to be merged. The paths for the .scss files have not been changed because of the problem below.

There seems to be a problem with webpack/css-loader/sass-loader not recognizing the resolved paths. While preparing to `npm run test`, `npm run build-renderer` fails when resolved-paths for scss imports: 
```
 ERROR in ./node_modules/css-loader?{"modules":true,"importLoaders":1,"localIdentName":"[name]__[local]__[hash:base64:5]"}!./node_modules/sass-loader/lib/loader.js!./app/routes/wallet/components/Wallet.scss
    Module build failed: 
    @import 'variables.scss';
    ^
          File to import not found or unreadable: variables.scss.
```

**Comment by jackmallers** [comment]
Beautiful @VonIobro, nice first contribution! Yeah if you wanna create an issue we can take care of that issue at some point.

I actually don't mind styled components myself. One day when this project is in a much more stable place and goes through a large refactor we can make that switch

**Comment by thisconnect** [comment]
this is non standard esmodule path resolving correct? in case you want to use another builder this might not work anymore

**Pull request merged**
