### PR TITLE
feat(ui): add Dropdown component

### PR DESCRIPTION
**Pull request by mrfelton**
## Description:

Add new `Dropdown` that we can use throughout the app.

## Motivation and Context:

 - Component needed for implementing new Pay/Request screens.
 - Create reusable component for cryptocurrency unit selection
 - Prepare to DRY up codebase
 - Implement new dropdown styles.

## How Has This Been Tested?

 - `yarn storybook` and navigate to `/ Components / Dropdown`
 - test all crypto selector dropdowns in the app

## Screenshots (if appropriate):

screenshot 2018-10-23 20 23 09

## Types of changes:

New feature

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [x] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

**Comment by mrfelton** [comment]
@JimmyMow I've added an additional commit to this PR which updates all of the currency selector dropdowns in the app to use the new component - removing over 400 lines of code in the process :)

**Comment by JimmyMow** [comment]
Concept ACK.

One tiny nit @mrfelton. Per our design mocks the crypto dropdown should be bottom aligned on the home screen. Here is the design mock:

screen shot 2018-10-31 at 9 37 29 pm

Here is what this PR shows:

screen shot 2018-10-31 at 9 36 21 pm

I've added `align-self: flex-end;` via the console to the dropdown container and removed the padding on the button to achieve this:

screen shot 2018-10-31 at 9 36 04 pm

After that small change is added this is ready to be merged 🎊

**Comment by mrfelton** [comment]
Thanks. That's fixed now @JimmyMow

**Comment by JimmyMow** [comment]
Tested ACK 514aad8

**Pull request merged**
