### PR TITLE
feat(ui): add contextual help component

### PR DESCRIPTION
**Pull request by mrfelton**
## Description:

Rebase #1501 and make some minor adjustments to the style so that it's more inline with our existing tooltip styles and makes better use of rebass style props.

## Motivation and Context:

Addresses #1291

## How Has This Been Tested?

Manually

## Screenshots (if appropriate):

image

## Types of changes:

New Feature

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [ ] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

**Comment by JimmyMow** [comment]
@mrfelton why does the copy there say it will be visible to you only? That isn't true. When the receiver decodes the request they will see the memo. The memo is intended to provide context to the user paying the request

**Comment by mrfelton** [comment]
You're right @JimmyMow ! I think this was just taken directly from the visual in Zeplin. Could you provide some updated verbiage please?

**Comment by JimmyMow** [comment]
Sure. How about:

`Add some describer text to your payment request for the recipient to see when paying.`

**Comment by mrfelton** [comment]
@JimmyMow I've updated the text for this.

**Pull request merged**
