### PR TITLE
refactor: move styles to styles directory

### PR DESCRIPTION
**Pull request by mrfelton**
Spin off from https://github.com/LN-Zap/zap-desktop/pull/509

### CODE REVIEW

**Comment by Empact** [comment]
Could you also update the lint-styles paths in package.json?

**Comment by mrfelton** [comment]
I've extracted those path definitions out into an npm config variable and updated the scripts to use that.

**Comment by mrfelton** [comment]
I have actually noticed that none of the stylesheets in app/components are being linted. I will fix in a follow up PR as after fixing, many of the stylesheets will need to be re-linted and fixed where they are broken

**Comment by mrfelton** [comment]
rebased

**Comment by Empact** [comment]
utACK bca5761

**Pull request merged**
