### PR TITLE
Refactor containers and routing

### PR DESCRIPTION
**Pull request by mrfelton**
## Description:

Refactor Containers and Routes in order to make the code a little more readable, reduce duplication, and prepare the codebase for integration of the new Home screen.

- Update from [`react-router-redux`](https://github.com/reactjs/react-router-redux) (deprecated) to [`connected-react-router`](https://github.com/supasate/connected-react-router)
- Use routing for navigation between primary containers:
  - `/` redirects to `/onboarding` currently
  - `/onboarding` shows the current onboarding process
  - `/syncing` shows the syncing screen, which redirects `/app` on completion)
  - `/app` shows the main wallet screen.
- Break out the Root container into several smaller containers that are responsible for connecting themselves to the Redux store (improve readability and performance).
- Unbundle the `Syncing` Component from the Onboarding section and hook up to router so that it can be access by navigating to `/syncing' (we want to be able to load existing wallets and initiate syncing outside of the context of the onboarding process)
- Reduce code duplication
  - Create `TitleBar` component and implement once at the top level
  - Create `withLoading` HOC and use to display the loading screen when needed.

**NOTE:** This is a bit of a large PR unfortunately, but the changes are very much intertwined and it would have created a lot of extra work to try and break it out into a staggered changeset.

## Motivation and Context:

DRY up the codebase a little. Break up large hard to read containers. Prepare the app for integration of the new Home screen.

## How Has This Been Tested?

Manually

## Types of changes:

Refactor

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

**Comment by JimmyMow** [comment]
@mrfelton it seems the request view got a little messed up, see screenshot below.

screen shot 2018-10-22 at 10 52 39 am

i'll keep clicking around and playing with this branch and posting screenshots in here

**Comment by mrfelton** [comment]
Good catch @JimmyMow - that should be fixed now.

**Comment by JimmyMow** [comment]
@mrfelton It seems I'm getting 2 console errors that I'm not getting in master.

The first is on app start. Looks like the `theme` prop is undefined:
screen shot 2018-10-22 at 12 51 28 pm

Second occurs whenever I create a payment request:
screen shot 2018-10-22 at 12 54 47 pm

**Comment by JimmyMow** [comment]
Tested ACK 080f876

**Pull request merged**
