### PR TITLE
fix(ui): left-align column text

### PR DESCRIPTION
**Pull request by bolatovumar**
Addresses the weird gap between words in column issue from #636. See the last image and paragraph here: [https://github.com/LN-Zap/zap-desktop/issues/636#issuecomment-450604350](https://github.com/LN-Zap/zap-desktop/issues/636#issuecomment-450604350)

### CODE REVIEW

**Comment by bolatovumar** [comment]
I tried out using 16px font size (currently set at 10px) on my MacBook Air (non-retina) and it looks much more readable. My only concern for increasing the font size here would be that it might show up too big on retina screens. I doubt it would be an issue but would like someone to confirm.

**Comment by bolatovumar** [comment]
And as far as legibility for non-retina screens goes I found that using `font-weight: 400;` instead of the currently used `font-weight: 300;` works wonderfully. Not sure whether retina screens would be negatively impact by this change though.

**Comment by mrfelton** [comment]
@bolatovumar regarding the font-sizes - I think the best way to do this is to take a more holistic approach and make our font-sizes (and other page elements) responsive via breakpoints.

I don't think we really want to adjust the default font-sizes or weights, but we can tailor for smaller/larger screen sizes.

Rebass (our theme system, https://github.com/rebassjs/rebass) already supports responsive theming and I actually already have a PR in my local branch that makes a start at making our font-sizes responsive using this approach. If you are interested on taking this on let me know and I can share what I have with you.

**Comment by bolatovumar** [comment]
@mrfelton do you mean you would prefer to adjust font sizes/weights for NON-RETINA displays through media queries that target these displays rather than enable the change for all displays?

The issue with font sizes and weights here is not due to the viewport or resolution being too small but due to the font-sizes themselves being too small and therefore rendering less than ideally.

For example, I'm having trouble reading some of the text without glasses (especially within the menu where the fiat/theme/language are set). It's a lot better with the glasses but still quite small. I generally find that using <12px font sizes in UIs is a no-go from the accessibility perspective especially if light font weights are used.

The type scale for the Material Design system from Google shows how they use Roboto at various sizes [(https://material.io/design/typography/the-type-system.html#)](https://material.io/design/typography/the-type-system.html#). Notice that the 10px size is used in all-caps only and in the Regular font-weight.

**Comment by mrfelton** [comment]
@bolatovumar Yes, I was suggesting that we adjust font sizes for specific breakpoints but leave the defaults / base sizes as is. Reason being that we've been through a design process and these were the sizes and weights that were picked by the designers, so changing this would have an impact on the designs and overall look and feel. Not saying that the current font sizes are right or perfect, just that our current look and feel has been designed with these sizes.

The reason that I was looking at adjusting the font sizes via breakpoints is that we know that when the app is displayed in full screen mode on a large hi-res retina display, the fonts look very small and there is a lot of space on the screen - so making fonts larger when there is is more screen space would be nice.  But, making the font sizes larger on smaller screens / resolutions could cause some issues in some parts of the app, with things not fitting onto the page fully without requiring the user to scroll - which is something that we want to avoid if possible.

I generally work on a mac with a retina display, at a res of 1440 x x900 and there the font size is good (for me). But I think your point about accessibility is a valid one and we certainly don't want users having to squint at the screen to read things.

@bolatovumar could you open a separate issue to carry on this discussion about font sizes please, so that it doesn't get lost in this closed PR? Thanks.

**Pull request merged**
